agent:
  name: deepseek_ocr_agent
  description: "Agent to read images and perform DeepSeek OCR (text extraction only)."
  attributes:
    agent_mode: "generator"

templates:
  - template_name: InputTemplate
    class_name: InputTemplate
    attributes: {}

  - template_name: FolderImageDatasetCV2
    class_name: FolderImageDatasetCV2
    template_input: InputTemplate
    attributes:
      load_on_init: True
      root_dir: "."
      data_dir: "artifacts"
      pattern: "recipe.jpg"

  - template_name: DeepSeekOCRInference
    class_name: DeepSeekOCRInference
    template_input: FolderImageDatasetCV2
    attributes:
      prompt: "OCR the image."
      enable_grounding: false
      mode: base
      init_args:
        pretrained_model_name_or_path: deepseek-ai/DeepSeek-OCR
        torch_dtype: auto
        attn_implementation: flash_attention_2
        trust_remote_code: true
        use_safetensors: true
